spring:
  thymeleaf:
    cache: false
  datasource:
  generate-unique-name: false
  datasource.name: tacocloud
  data:
    mongodb:
      host: localhost
      port: 27017
      embedded:
        version: 4.0.2-beta
